-- ////////////////////////////////////////////////////////////////
-- Version : Russian ( by Maus )
-- \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

if ( GetLocale() == "ruRU" ) then

ZHUNTER_MAGMADAR = "Магмадар"
ZHUNTER_FLAMEGORE = "Пламегор"
ZHUNTER_CHROMMAGUS = "Хромаггус"
ZHUNTER_HUHURAN = "Принцесса Хухуран"
ZHUNTER_GLUTH = "Глут"

ZHUNTER_TRANQCASTYOU = "Вы применяете заклинание \"Усмиряющий выстрел\"%."
ZHUNTER_TRANQMISSYOU = "Ваше заклинание \"Усмиряющий выстрел\" не попадает по вам%."
ZHUNTER_TRANQFAILYOU = "Вам не удалось развеять заклинание (.+) \"Исступление\"%."
ZHUNTER_TRANQCASTOTHER = "(.*)\"Усмиряющий выстрел\" на (.*) "
ZHUNTER_TRANQMISSOTHER = "(.+) применяет заклинание \"Усмиряющий выстрел\"(.*)"
ZHUNTER_TRANQFAILOTHER = "(.+) не удалось развеять заклинание (.+) \"Исступление\"%."
ZHUNTER_GAINFRENZY = "(.+) получает эффект \"Исступление\"%."
ZHUNTER_FRENZY = "исступление"

ZHUNTER_YOU = "Вы"
ZHUNTER_HUNTER = "Охотник"
ZHUNTER_BOWS = "Луки"
ZHUNTER_CROSSBOWS = "Арбалеты"
ZHUNTER_GUNS = "Ружья"
ZHUNTER_AFFLICTED_DAZED = "(.+) (.+) (.*)Замедление%."

ZHUNTER_BULLETS_LIGHT = "Легкий патрон"
ZHUNTER_BULLETS_CRAFTLIGHT = "Легкий искусно изготовленный патрон"
ZHUNTER_BULLETS_FLASH = "Мелкая пулька"
ZHUNTER_BULLETS_HEAVY = "Тяжелый патрон"
ZHUNTER_BULLETS_PEBBLE = "Шлифованный метательный камень"
ZHUNTER_BULLETS_CRAFTHEAVY = "Тяжелый искусно изготовленный патрон"
ZHUNTER_BULLETS_SOLID = "Твердый патрон"
ZHUNTER_BULLETS_CRAFTSOLID = "Твердый искусно изготовленный патрон"
ZHUNTER_BULLETS_EXPLODING = "Разрывной патрон"
ZHUNTER_BULLETS_MITHRILSLUG = "Бронебойные мифриловые пули"
ZHUNTER_BULLETS_ACCURATE = "Точные пули"
ZHUNTER_BULLETS_GYROSHOT = "Мифриловый гиро%-патрон"
ZHUNTER_BULLETS_ICETHREADED = "Пронизанная льдом пуля"
ZHUNTER_BULLETS_THORIUM = "Ториевые патроны"
ZHUNTER_BULLETS_ROCKSHARD = "Каменноосколочная беспатронная пуля"
ZHUNTER_BULLETS_CANNONBALL = "Ядра для мини-пушки"

ZHUNTER_ARROWS_ROUGH = "Грубая стрела"
ZHUNTER_ARROWS_SHARP = "Острая стрела"
ZHUNTER_ARROWS_RAZOR = "Стрела-бритва"
ZHUNTER_ARROWS_FEATHER = "Оперенная стрела"
ZHUNTER_ARROWS_PRECISION = "Точная стрела"
ZHUNTER_ARROWS_JAGGED = "Зазубренная стрела"
ZHUNTER_ARROWS_ICETHREADED = "Пронизанная льдом стрела"
ZHUNTER_ARROWS_THORIUM = "Стрела с ториевым наконечником"
ZHUNTER_ARROWS_DOOMSHOT = "Роковой патрон"

ZHUNTER_HUNTERSMARK = "Метка охотника"
ZHUNTER_RAPIDFIRE = "Быстрая стрельба"
ZHUNTER_IMPROVEDHAWK = "Скорострельность"
ZHUNTER_BERSERKING = "Берсерк"
ZHUNTER_AUTO = "Автоматическая стрельба"
ZHUNTER_AIMED = "Прицельный выстрел"
ZHUNTER_SERPENT = "Укус змеи"
ZHUNTER_SCORPID = "Укус скорпида"
ZHUNTER_VIPER = "Укус гадюки"
ZHUNTER_ARCANE = "Чародейский выстрел"
ZHUNTER_CONCUSSIVE = "Контузящий выстрел"
ZHUNTER_TRANQUILIZING = "Усмиряющий выстрел"
ZHUNTER_DISTRACTING = "Отвлекающий выстрел"
ZHUNTER_VOLLEY = "Град стрел"

ZHUNTER_TRACK_HUMANOIDS = "Выслеживание гуманоидов"
ZHUNTER_TRACK_HIDDEN = "Выслеживание скрытых"
ZHUNTER_TRACK_BEASTS = "Выслеживание животных"
ZHUNTER_TRACK_ELEMENTALS = "Выслеживание элементалей"
ZHUNTER_TRACK_DEMONS = "Выслеживание демонов"
ZHUNTER_TRACK_DRAGONKIN = "Выслеживание драконов"
ZHUNTER_TRACK_UNDEAD = "Выслеживание нежити"
ZHUNTER_TRACK_GIANTS = "Выслеживание великанов"
ZHUNTER_TRACK_MINERALS = "Поиск минералов"
ZHUNTER_TRACK_HERBS = "Поиск трав"
ZHUNTER_TRACK_TREASURE = "Поиск сокровища"

ZHUNTER_FEIGN = "Притвориться мертвым"
ZHUNTER_TRAP_FREEZING = "Замораживающая ловушка"
ZHUNTER_TRAP_FROST = "Ледяная ловушка"
ZHUNTER_TRAP_IMMOLATION = "Обжигающая ловушка"
ZHUNTER_TRAP_EXPLOSIVE = "Взрывная ловушка"

ZHUNTER_ASPECT_HAWK = "Дух ястреба"
ZHUNTER_ASPECT_MONKEY = "Дух обезьяны"
ZHUNTER_ASPECT_CHEETAH = "Дух гепарда"
ZHUNTER_ASPECT_BEAST = "Дух зверя"
ZHUNTER_ASPECT_PACK = "Дух стаи"
ZHUNTER_ASPECT_WILD = "Дух дикой природы"

ZHUNTER_PET_EYES = "Звериный глаз"
ZHUNTER_PET_DISMISS = "Прогнать питомца"
ZHUNTER_PET_MEND = "Лечение питомца"
ZHUNTER_PET_FEED = "Кормление питомца"
ZHUNTER_PET_CALL = "Призыв питомца"
ZHUNTER_PET_REVIVE = "Воскрешение питомца"
ZHUNTER_PET_LORE = "Знание зверя"
ZHUNTER_PET_TRAINING = "Дрессировка"
ZHUNTER_PET_TAMING = "Приручение зверя"
ZHUNTER_PET_FEAR = "Отпугивание зверя"

end